[package]
name = "collapsed_matrices"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.14.0"
factorial = "0.2.1"
rayon = "1.5.3"
euclid = "0.22.7"
rand = "0.8.5"